version: "3.9"
services:
  pbr-th:
    build: .
    environment:
      TWITTER_LANGUAGE: "es"
      TWITTER_HASHTAG: "#example"
      TWITTER_SAMPLE: "true"
      REDIS_HOST: "redis:6379"
      REDIS_QUEUE: "TweetsFound"
      LOG_LEVEL: "DEBUG"
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"