version: "3.9"
services:
  pbr-th:
    image: golang:1.15-alpine
    command: [ "sleep", "infinity"]
    container_name: pbr-th-local
    environment:
      CONSUMER_KEY: "${CONSUMER_KEY}"
      CONSUMER_SECRET: "${CONSUMER_SECRET}"
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      TWITTER_LANGUAGE: "es"
      TWITTER_HASHTAG: "#example"
      TWITTER_SAMPLE: "true"
      REDIS_HOST: "redis:6379"
      REDIS_QUEUE: "RawTweets"
      LOG_LEVEL: "DEBUG"
    working_dir: /go/src
    volumes:
      - type: bind
        source: ./
        target: /go/src
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"